package com.example.retrofitdemo.model

/*
Data class for the List of the Album Items generated by our Json to Kotlin plugin.

Each Album has an ID, TITLE, and UserID.

We have to use Data classes when we want to parse JSON objects into Kotlin.
 */
data class AlbumsDataClassItem(
    val id: Int,
    val title: String,
    val userId: Int
)