package com.example.retrofitdemo.model

/**
 * This data class holds the array list of all the items in the album class.
 *
 * This class was generated by JSON to Kotlin plugin.
 */
class AlbumsDataClass : ArrayList<AlbumsDataClassItem>()